<?php

use App\Http\Controllers\Api\ArrearController;
use App\Http\Controllers\Api\AuditController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ChatController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\DocumentController;
use App\Http\Controllers\Api\EventController;
use App\Http\Controllers\Api\InspectionController;
use App\Http\Controllers\Api\MaintenanceController;
use App\Http\Controllers\Api\MarketplaceController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\PatrimonyController;
use App\Http\Controllers\Api\RentalApplicationController;
use App\Http\Controllers\Api\RentalController;
use Illuminate\Support\Facades\Route;

Route::get('/ping', fn () => response()->json(['success' => true, 'message' => 'API VIMMO opérationnelle.']));
Route::get('/listings', [MarketplaceController::class, 'listings']);
Route::get('/listings/{listing}', [MarketplaceController::class, 'show']);
Route::get('/event-categories', [EventController::class, 'categories']);
Route::get('/events', [EventController::class, 'index']);
Route::get('/events/{event}', [EventController::class, 'show']);
Route::get('/receipts/verify/{token}', [RentalController::class, 'verifyReceipt']);
Route::prefix('auth')->middleware('throttle:10,1')->group(function () {
    Route::post('/register', [AuthController::class, 'register']);
    Route::post('/login', [AuthController::class, 'login']);
    Route::post('/forgot-password', [AuthController::class, 'forgot']);
    Route::post('/reset-password', [AuthController::class, 'reset']);
    Route::post('/verify-otp', [AuthController::class, 'verifyOtp'])->middleware('throttle:6,1');
    Route::post('/resend-otp', [AuthController::class, 'resendOtp'])->middleware('throttle:3,1');
});

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/dashboard', DashboardController::class);
    Route::get('/auth/me', [AuthController::class, 'me']);
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::get('/auth/sessions', [AuthController::class, 'sessions']);
    Route::delete('/auth/sessions/{session}', [AuthController::class, 'revokeSession']);
    Route::delete('/auth/sessions', [AuthController::class, 'revokeOtherSessions']);
    Route::put('/auth/profile', [AuthController::class, 'update']);
    Route::put('/auth/password', [AuthController::class, 'password']);
    Route::get('/audit-logs', [AuditController::class, 'index']);
    Route::get('/favorites', [MarketplaceController::class, 'favorites']);
    Route::post('/listings/{listing}/favorite', [MarketplaceController::class, 'favorite']);
    Route::delete('/listings/{listing}/favorite', [MarketplaceController::class, 'unfavorite']);
    Route::get('/rental-applications', [RentalApplicationController::class, 'index']);
    Route::post('/listings/{listing}/applications', [RentalApplicationController::class, 'store']);
    Route::patch('/rental-applications/{application}/status', [RentalApplicationController::class, 'status'])->middleware('role:owner');
    Route::delete('/rental-applications/{application}', [RentalApplicationController::class, 'withdraw']);
    Route::get('/saved-searches', [MarketplaceController::class, 'savedSearches']);
    Route::post('/saved-searches', [MarketplaceController::class, 'saveSearch']);
    Route::delete('/saved-searches/{search}', [MarketplaceController::class, 'deleteSearch']);
    Route::get('/visits', [MarketplaceController::class, 'visits']);
    Route::post('/listings/{listing}/visits', [MarketplaceController::class, 'visit']);
    Route::patch('/visits/{visit}/status', [MarketplaceController::class, 'visitStatus'])->middleware('role:owner');
    Route::middleware('role:owner')->group(function () {
        Route::get('/properties', [MarketplaceController::class, 'properties']);
        Route::get('/owner/listings', [MarketplaceController::class, 'ownerListings']);
        Route::post('/properties', [MarketplaceController::class, 'storeProperty']);
        Route::put('/properties/{property}', [MarketplaceController::class, 'updateProperty']);
        Route::delete('/properties/{property}', [MarketplaceController::class, 'deleteProperty']);
        Route::post('/properties/{property}/units', [MarketplaceController::class, 'storeUnit']);
        Route::post('/listings', [MarketplaceController::class, 'storeListing']);
        Route::put('/listings/{listing}', [MarketplaceController::class, 'updateListing']);
        Route::delete('/listings/{listing}', [MarketplaceController::class, 'deleteListing']);
        Route::post('/units/{unit}/tenant', [RentalController::class, 'createTenant']);
        Route::post('/contracts', [RentalController::class, 'storeContract']);
        Route::post('/payments/{payment}/confirm', [RentalController::class, 'confirm']);
        Route::post('/payments/{payment}/reject', [RentalController::class, 'reject']);
        Route::patch('/maintenance/{maintenance}/status', [MaintenanceController::class, 'status']);
        Route::get('/patrimony', [PatrimonyController::class, 'index']);
        Route::post('/patrimony', [PatrimonyController::class, 'store']);
        Route::get('/patrimony/shares', [PatrimonyController::class, 'shares']);
        Route::post('/patrimony/{property}/shares', [PatrimonyController::class, 'share']);
        Route::delete('/patrimony/shares/{share}', [PatrimonyController::class, 'revoke']);
    });
    Route::get('/units', [MarketplaceController::class, 'units'])->middleware('role:owner');
    Route::get('/tenants', [MarketplaceController::class, 'tenants'])->middleware('role:owner');
    Route::get('/patrimony/shared-with-me', [PatrimonyController::class, 'sharedWithMe']);
    Route::post('/patrimony/{property}/photos', [PatrimonyController::class, 'photos']);
    Route::post('/patrimony/{property}/documents', [PatrimonyController::class, 'document']);
    Route::get('/units/{unit}/timeline', [RentalController::class, 'unitTimeline']);
    Route::get('/contracts', [RentalController::class, 'contracts']);
    Route::get('/rent-schedules', [RentalController::class, 'schedules']);
    Route::get('/payments', [RentalController::class, 'payments']);
    Route::post('/payments', [RentalController::class, 'pay'])->middleware('role:tenant');
    Route::post('/payments/record', [RentalController::class, 'recordPayment'])->middleware('role:owner');
    Route::get('/payments/{payment}/proof', [RentalController::class, 'downloadProof']);
    Route::get('/receipts', [RentalController::class, 'receipts']);
    Route::get('/receipts/{receipt}/download', [RentalController::class, 'downloadReceipt']);
    Route::get('/documents', [DocumentController::class, 'index']);
    Route::post('/documents', [DocumentController::class, 'store'])->middleware('role:owner');
    Route::get('/documents/{media}/download', [DocumentController::class, 'download']);
    Route::get('/inspections', [InspectionController::class, 'index']);
    Route::post('/inspections', [InspectionController::class, 'store'])->middleware('role:owner');
    Route::get('/inspections/{inspection}', [InspectionController::class, 'show']);
    Route::post('/inspections/{inspection}/items/{item}/media', [InspectionController::class, 'addMedia']);
    Route::post('/inspections/{inspection}/validate', [InspectionController::class, 'validateInspection']);
    Route::post('/inspections/{inspection}/dispute', [InspectionController::class, 'dispute']);
    Route::post('/inspections/{inspection}/disputes/{dispute}/respond', [InspectionController::class, 'respond'])->middleware('role:owner');
    Route::post('/inspections/{inspection}/revisions', [InspectionController::class, 'revise']);
    Route::get('/inspections/{inspection}/comparison', [InspectionController::class, 'compare']);
    Route::get('/inspections/{inspection}/download', [InspectionController::class, 'downloadPdf']);
    Route::get('/maintenance', [MaintenanceController::class, 'index']);
    Route::post('/maintenance', [MaintenanceController::class, 'store'])->middleware('role:tenant');
    Route::get('/maintenance/{maintenance}', [MaintenanceController::class, 'show']);
    Route::post('/maintenance/{maintenance}/comments', [MaintenanceController::class, 'comment']);
    Route::get('/arrears', [ArrearController::class, 'index'])->middleware('role:owner');
    Route::post('/arrears/{schedule}/remind', [ArrearController::class, 'remind'])->middleware('role:owner');
    Route::get('/conversations', [ChatController::class, 'index']);
    Route::post('/conversations', [ChatController::class, 'store']);
    Route::get('/conversations/{conversation}/messages', [ChatController::class, 'messages']);
    Route::post('/conversations/{conversation}/messages', [ChatController::class, 'send']);
    Route::get('/media/{media}/download', [PatrimonyController::class, 'download']);
    Route::get('/organizer/events', [EventController::class, 'mine'])->middleware('role:organizer');
    Route::get('/organizer/sales', [EventController::class, 'sales'])->middleware('role:organizer');
    Route::post('/organizer/events', [EventController::class, 'store'])->middleware('role:organizer');
    Route::match(['put', 'post'], '/organizer/events/{event}', [EventController::class, 'update'])->middleware('role:organizer');
    Route::delete('/organizer/events/{event}', [EventController::class, 'archive'])->middleware('role:organizer');
    Route::post('/organizer/tickets/scan', [EventController::class, 'scan'])->middleware('role:organizer');
    Route::post('/events/{event}/orders', [EventController::class, 'order']);
    Route::get('/tickets', [EventController::class, 'tickets']);
    Route::post('/ticket-orders/{order}/cancel',[EventController::class, 'cancelOrder']);
    Route::get('/notifications',[NotificationController::class, 'index']);
    Route::put('/notifications/read-all',[NotificationController::class, 'readAll']);
    Route::put('/notifications/{id}/read',[NotificationController::class, 'read']);
});
Route::post('/properties/{property}/media',[MarketplaceController::class, 'storePropertyMedia'])->middleware(['auth:sanctum', 'role:owner']);
